label_dataset:
  name: matterport3d
  root_path: ./Dataset/Matterport3D/
  list_path: ./datasets/matterport3d_train.txt
  args:
    height: 504
    width: 1008
    repeat: 66097
    augment_color: False
    augment_flip: True
    augment_rotation: True
  batch_size: 4
  num_workers: 4

unlabel_dataset:
  name: zind
  root_path:  ./Dataset/zind
  list_path: ./datasets/zind_diverse360.txt
  args:
    height: 504
    width: 1008
    repeat: 1
    augment_color: True
    augment_flip: True
    augment_rotation: True
  batch_size: 4
  num_workers: 4

val_dataset:
  name: matterport3d
  root_path: ./Matterport3D/
  list_path: ./datasets/matterport3d_test.txt
  args:
    height: 504
    width: 1008
    repeat: 1
    augment_color: False
    augment_flip: False
    augment_rotation: False
  batch_size: 1
  num_workers: 4

model:
  name: student_model_conv
  args:
    midas_model_type: vits
    min_depth: 0.01
    max_depth: 10.0
    lora: True
    train_decoder: True

loss: [silog]
loss_weights: [1.0, 1.0, 1.0, 1.0]

mobius:
  conduct: True
  vertical_res: 18
  zoom_res: 0.2

optimizer:
  lr: 1.e-4
epoch_max: 20
log_frequency: 40

epoch_val: 1
epoch_save: 10

